name: linux_qm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - rdkit
  - xtb
  - crest
  - cclib
  - scikit-learn
  - scipy
  - py3Dmol
  - notebook
  # molli deps
  - colorama
  - PyYAML
  - joblib
  - threadpoolctl